---
- name: Deploy Artifact to Localhost
  hosts: localhost
  become: true
  become_user: barath
  become_method: su

  tasks:
    - name: Copy the artifact to the target location
      copy:
        src: "/var/lib/jenkins/workspace/experiment8/target/testing-1.0-SNAPSHOT.jar"
        dest: "/home/barath/Desktop/t.jar"
